version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/weather-react
      overwrite: true
hooks:
    BeforeInstall:
        - location: scripts/start_server
          timeout: 300
          runas: root
